### ISSUE TITLE
How to use SwipeDismissTouchListener with Linear Layout or other ViewGroup

### ISSUE THREAD

**Issue by Kuoyhout** [romannurik/Android-SwipeToDismiss#16]
I implement SwipeDismissTouchListener with LinearLayout & other ViewGroup that contain other views, but swiping both left and right doesn't do anything. I have tested it with a Button it works fine.

**Comment by aneeskA** [comment]
This suggestion worked for me! Thanks a lot for posting this fix.

**Comment by aneeskA** [comment]
Now for removeView is not removing my linearlayout. Any idea?

**Comment by Rakeshkotha1** [comment]
I have Changed the return value to true but the view is recreating even after the removeView is Called .
Any idea about this?

**Comment by aneeskA** [comment]
It is recreating because the deletion is not done from the correct layout. The following example gives you a sample of code that is working for me. Note the variable linear_layout .

viewPlanRow = inflater.inflate(R.layout.layout_xml, null);
viewPlanRow.setOnTouchListener(new SwipeDismissTouchListener(
			.... 
			@Override
			public void onDismiss(View view, Object token) {
				linear_layout.removeView(view);
			}
		}));
linear_layout.addView(viewPlanRow);
